//
//  DCAvailability.h
//  DCAvailability
//
//  Created by David Clark on 5/02/2016.
//  Copyright © 2016 David Clark. All rights reserved.
//

#import <Foundation/NSObjCRuntime.h>

// Redefine some macros to generate warnings if code is used that was added to the API after the Deployment Target
//
// There are two way that the availability checking works
//
// 1. __AVAILABILITY_INTERNAL__IPHONE_XXX macros
// 2. NS_AVAILABLE_IOS macro
//
// In case 1, each macro is redefined in the case where the api version in question is between the min and max for
// the build, i.e. the API was introduced after the Deployment Target. The new macro makes the usage deprecated,
// and weak linked. Special consideration is required
//
// For case 2, there are macros created for every possible value of the argument to the macro, these default macros
// just do what the original NS_AVAILABLE_IOS did ("route" to CF_AVAILABLE_IOS which uses "availability" directly. The
// NS_AVAILABLE_IOS is redefined to evaluate the new macros depending on the argument. The default macros are then
// redefined in the case where the api version in question is between the min and max for the build, i.e. the API
// was introduced after the Deployment Target. The new macro makes the usage deprecated, and weak linked.


// A default macro for each case that does what the original NS_AVAILABLE_IOS does
#define DC_AVAILABILITY_2_0(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_2_1(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_2_2(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_3_0(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_3_1(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_3_2(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_4_0(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_4_1(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_4_2(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_4_3(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_5_0(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_5_1(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_6_0(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_6_1(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_7_0(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_7_1(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_8_0(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_8_1(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_8_2(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_8_3(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_8_4(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_9_0(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_9_1(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_9_2(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_9_3(_ios) CF_AVAILABLE_IOS(_ios)
#define DC_AVAILABILITY_10_0(_ios) CF_AVAILABLE_IOS(_ios)

// Macro to force the deprecated message, do the weak import, when needed
#define DC_DEPRECATED_NEWAPI(_ios) __attribute__((deprecated("Available starting API " #_ios ", which is newer than the Deployment Target"), weak_import))

// Redefine the old availability macros (used when "availability" is not used) and the default macros above to force
// the deprecation when the version falls into the weak link range also redefine the other macros

#if __IPHONE_2_0 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_2_0 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_2_0
#define __AVAILABILITY_INTERNAL__IPHONE_2_0 DC_DEPRECATED_NEWAPI(2_0)
#undef DC_AVAILABILITY_2_0
#define DC_AVAILABILITY_2_0(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_2_1 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_2_1 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_2_1
#define __AVAILABILITY_INTERNAL__IPHONE_2_1 DC_DEPRECATED_NEWAPI(2_1)
#undef DC_AVAILABILITY_2_1
#define DC_AVAILABILITY_2_1(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_2_2 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_2_2 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_2_2
#define __AVAILABILITY_INTERNAL__IPHONE_2_2 DC_DEPRECATED_NEWAPI(2_2)
#undef DC_AVAILABILITY_2_2
#define DC_AVAILABILITY_2_2(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_3_0 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_3_0 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_3_0
#define __AVAILABILITY_INTERNAL__IPHONE_3_0 DC_DEPRECATED_NEWAPI(3_0)
#undef  __AVAILABILITY_INTERNAL__IPHONE_3_0_DEP__IPHONE_7_0
#define __AVAILABILITY_INTERNAL__IPHONE_3_0_DEP__IPHONE_7_0 DC_DEPRECATED_NEWAPI(3_0)
#undef DC_AVAILABILITY_3_0
#define DC_AVAILABILITY_3_0(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_3_1 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_3_1 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_3_1
#define __AVAILABILITY_INTERNAL__IPHONE_3_1 DC_DEPRECATED_NEWAPI(3_1)
#undef DC_AVAILABILITY_3_1
#define DC_AVAILABILITY_3_1(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_3_2 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_3_2 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_3_2
#define __AVAILABILITY_INTERNAL__IPHONE_3_2 DC_DEPRECATED_NEWAPI(3_2)
#undef DC_AVAILABILITY_3_2
#define DC_AVAILABILITY_3_2(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_4_0 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_4_0 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_4_0
#define __AVAILABILITY_INTERNAL__IPHONE_4_0 DC_DEPRECATED_NEWAPI(4_0)
#undef  __AVAILABILITY_INTERNAL__IPHONE_4_0_DEP__IPHONE_6_0
#define __AVAILABILITY_INTERNAL__IPHONE_4_0_DEP__IPHONE_6_0 DC_DEPRECATED_NEWAPI(4_0)
#undef DC_AVAILABILITY_4_0
#define DC_AVAILABILITY_4_0(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_4_1 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_4_1 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_4_1
#define __AVAILABILITY_INTERNAL__IPHONE_4_1 DC_DEPRECATED_NEWAPI(4_1)
#undef DC_AVAILABILITY_4_1
#define DC_AVAILABILITY_4_1(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_4_2 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_4_2 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_4_2
#define __AVAILABILITY_INTERNAL__IPHONE_4_2 DC_DEPRECATED_NEWAPI(4_2)
#undef DC_AVAILABILITY_4_2
#define DC_AVAILABILITY_4_2(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_4_3 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_4_3 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_4_3
#define __AVAILABILITY_INTERNAL__IPHONE_4_3 DC_DEPRECATED_NEWAPI(4_3)
#undef  __AVAILABILITY_INTERNAL__IPHONE_4_3_DEP__IPHONE_7_0
#define __AVAILABILITY_INTERNAL__IPHONE_4_3_DEP__IPHONE_7_0 DC_DEPRECATED_NEWAPI(4_3)
#undef DC_AVAILABILITY_4_3
#define DC_AVAILABILITY_4_3(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_5_0 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_5_0 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_5_0
#define __AVAILABILITY_INTERNAL__IPHONE_5_0 DC_DEPRECATED_NEWAPI(5_0)
#undef  __AVAILABILITY_INTERNAL__IPHONE_5_0_DEP__IPHONE_6_0
#define __AVAILABILITY_INTERNAL__IPHONE_5_0_DEP__IPHONE_6_0 DC_DEPRECATED_NEWAPI(5_0)
#undef DC_AVAILABILITY_5_0
#define DC_AVAILABILITY_5_0(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_5_1 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_5_1 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_5_1
#define __AVAILABILITY_INTERNAL__IPHONE_5_1 DC_DEPRECATED_NEWAPI(5_1)
#undef DC_AVAILABILITY_5_1
#define DC_AVAILABILITY_5_1(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_6_0 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_6_0 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_6_0
#define __AVAILABILITY_INTERNAL__IPHONE_6_0 DC_DEPRECATED_NEWAPI(6_0)
#undef  __AVAILABILITY_INTERNAL__IPHONE_6_0_DEP__IPHONE_7_0
#define __AVAILABILITY_INTERNAL__IPHONE_6_0_DEP__IPHONE_7_0 DC_DEPRECATED_NEWAPI(6_0)
#undef  __AVAILABILITY_INTERNAL__IPHONE_6_0_DEP__IPHONE_9_0
#define __AVAILABILITY_INTERNAL__IPHONE_6_0_DEP__IPHONE_9_0 DC_DEPRECATED_NEWAPI(6_0)
#undef DC_AVAILABILITY_6_0
#define DC_AVAILABILITY_6_0(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_6_1 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_6_1 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_6_1
#define __AVAILABILITY_INTERNAL__IPHONE_6_1 DC_DEPRECATED_NEWAPI(6_1)
#undef DC_AVAILABILITY_6_1
#define DC_AVAILABILITY_6_1(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_7_0 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_7_0 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_7_0
#define __AVAILABILITY_INTERNAL__IPHONE_7_0 DC_DEPRECATED_NEWAPI(7_0)
#undef DC_AVAILABILITY_7_0
#define DC_AVAILABILITY_7_0(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_7_1 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_7_1 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_7_1
#define __AVAILABILITY_INTERNAL__IPHONE_7_1 DC_DEPRECATED_NEWAPI(7_1)
#undef DC_AVAILABILITY_7_1
#define DC_AVAILABILITY_7_1(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_8_0 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_8_0 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_8_0
#define __AVAILABILITY_INTERNAL__IPHONE_8_0 DC_DEPRECATED_NEWAPI(8_0)
#undef DC_AVAILABILITY_8_0
#define DC_AVAILABILITY_8_0(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_8_1 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_8_1 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_8_1
#define __AVAILABILITY_INTERNAL__IPHONE_8_1 DC_DEPRECATED_NEWAPI(8_1)
#undef DC_AVAILABILITY_8_1
#define DC_AVAILABILITY_8_1(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_8_2 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_8_2 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_8_2
#define __AVAILABILITY_INTERNAL__IPHONE_8_2 DC_DEPRECATED_NEWAPI(8_2)
#undef DC_AVAILABILITY_8_2
#define DC_AVAILABILITY_8_2(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_8_3 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_8_3 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_8_3
#define __AVAILABILITY_INTERNAL__IPHONE_8_3 DC_DEPRECATED_NEWAPI(8_3)
#undef DC_AVAILABILITY_8_3
#define DC_AVAILABILITY_8_3(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_8_4 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_8_4 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_8_4
#define __AVAILABILITY_INTERNAL__IPHONE_8_4 DC_DEPRECATED_NEWAPI(8_4)
#undef DC_AVAILABILITY_8_4
#define DC_AVAILABILITY_8_4(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_9_0 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_9_0 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_9_0
#define __AVAILABILITY_INTERNAL__IPHONE_9_0 DC_DEPRECATED_NEWAPI(9_0)
#undef DC_AVAILABILITY_9_0
#define DC_AVAILABILITY_9_0(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_9_1 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_9_1 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_9_1
#define __AVAILABILITY_INTERNAL__IPHONE_9_1 DC_DEPRECATED_NEWAPI(9_1)
#undef DC_AVAILABILITY_9_1
#define DC_AVAILABILITY_9_1(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_9_2 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_9_2 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_9_2
#define __AVAILABILITY_INTERNAL__IPHONE_9_2 DC_DEPRECATED_NEWAPI(9_2)
#undef DC_AVAILABILITY_9_2
#define DC_AVAILABILITY_9_2(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_9_3 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_9_3 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_9_3
#define __AVAILABILITY_INTERNAL__IPHONE_9_3 DC_DEPRECATED_NEWAPI(9_3)
#undef DC_AVAILABILITY_9_3
#define DC_AVAILABILITY_9_3(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

#if __IPHONE_10_0 > __IPHONE_OS_VERSION_MIN_REQUIRED & __IPHONE_10_0 <= __IPHONE_OS_VERSION_MAX_ALLOWED
#undef  __AVAILABILITY_INTERNAL__IPHONE_10_0
#define __AVAILABILITY_INTERNAL__IPHONE_10_0 DC_DEPRECATED_NEWAPI(10_0)
#undef DC_AVAILABILITY_10_0
#define DC_AVAILABILITY_10_0(_ios) DC_DEPRECATED_NEWAPI(_ios)
#endif

// Reroute usages of the NS_AVAILABLE_IOS macro to our own version specific ones (possibly the default, possibly redefined)
#undef NS_AVAILABLE_IOS
#define NS_AVAILABLE_IOS(_ios) DC_AVAILABILITY_##_ios(_ios)
